{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ template "eric-enm-int-license-manager-db.serviceAccountName" . }}-serviceaccount
    namespace: {{ .Release.Namespace }}
{{- end -}}